"""Where report artifacts are kept.

Two implementations behind one small interface: a directory on disk for laptops
and CI, and a Blob container for the deployed application. The interface is
deliberately smaller than either backend — put, get, delete, exists — because
everything else the application needs to know about an artifact lives in the
``artifacts`` table, where it can be queried.

Paths are always relative and always generated by :func:`artifact_path`; a
caller never gets to hand a path in from outside, which is what keeps a
crafted filename from walking out of the container.
"""

from __future__ import annotations

import logging
import re
import shutil
import unicodedata
from pathlib import Path, PurePosixPath
from typing import Protocol, runtime_checkable

from .errors import CCReportError
from .settings import Settings, get_settings

logger = logging.getLogger("ccreport.storage")

_SAFE_CHARS = re.compile(r"[^A-Za-z0-9._-]+")
_MAX_STEM = 64


class StorageError(CCReportError):
    """The artifact store refused, or could not find what was asked for."""


def safe_filename(name: str, *, default: str = "attachment") -> str:
    """Reduce a provider-supplied filename to something safe to store.

    Attachment names arrive from mailboxes, which is to say from anyone who can
    send mail to a faculty member. ``../../etc/passwd``, a 400-character name,
    and a name that is entirely emoji are all realistic inputs.
    """
    name = unicodedata.normalize("NFKD", name or "").strip().replace("\x00", "")
    name = PurePosixPath(name.replace("\\", "/")).name
    suffix = PurePosixPath(name).suffix[:16]
    stem = name[: len(name) - len(suffix)] if suffix else name
    stem = _SAFE_CHARS.sub("-", stem).strip("-.")[:_MAX_STEM]
    suffix = _SAFE_CHARS.sub("", suffix)
    if not stem:
        stem = default
    return f"{stem}{suffix}" if suffix else stem


def artifact_path(report_id: str, artifact_id: str, filename: str) -> str:
    """The canonical blob path for one artifact."""
    return f"reports/{report_id}/{artifact_id}/{safe_filename(filename)}"


@runtime_checkable
class ArtifactStore(Protocol):
    """Byte storage addressed by a relative path."""

    def put(self, path: str, data: bytes, *, content_type: str = "application/octet-stream") -> str:
        """Store ``data``. Returns the path it was stored at."""
        ...

    def get(self, path: str) -> bytes: ...

    def exists(self, path: str) -> bool: ...

    def delete(self, path: str) -> bool: ...

    def delete_prefix(self, prefix: str) -> int: ...


def _validate(path: str) -> PurePosixPath:
    pure = PurePosixPath(path)
    if pure.is_absolute() or any(part in ("..", "") for part in pure.parts):
        raise StorageError(f"unsafe artifact path: {path!r}")
    return pure


class LocalArtifactStore:
    """A directory on disk. The laptop, CI, and Compose path."""

    kind = "local"

    def __init__(self, root: str | Path):
        self.root = Path(root).expanduser().resolve()
        self.root.mkdir(parents=True, exist_ok=True)

    def _resolve(self, path: str) -> Path:
        target = (self.root / _validate(path)).resolve()
        # Belt and braces: _validate already rejects traversal, but a symlink
        # inside the tree could still point outside it.
        if not target.is_relative_to(self.root):
            raise StorageError(f"artifact path escapes the store root: {path!r}")
        return target

    def put(self, path: str, data: bytes, *, content_type: str = "application/octet-stream") -> str:
        target = self._resolve(path)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        return path

    def get(self, path: str) -> bytes:
        target = self._resolve(path)
        try:
            return target.read_bytes()
        except FileNotFoundError as exc:
            raise StorageError(f"artifact not found: {path}") from exc

    def exists(self, path: str) -> bool:
        return self._resolve(path).is_file()

    def delete(self, path: str) -> bool:
        target = self._resolve(path)
        if not target.is_file():
            return False
        target.unlink()
        return True

    def delete_prefix(self, prefix: str) -> int:
        target = self._resolve(prefix)
        if not target.is_dir():
            return 0
        count = sum(1 for p in target.rglob("*") if p.is_file())
        shutil.rmtree(target)
        return count


class BlobArtifactStore:
    """Azure Blob Storage, reached with the App Service managed identity."""

    kind = "blob"

    def __init__(self, account_url: str, container: str, *, credential=None, client=None):
        self.account_url = account_url
        self.container = container
        self._credential = credential
        self._service = client
        self._ensured = False

    def _container_client(self):
        if self._service is None:
            try:
                from azure.identity import DefaultAzureCredential
                from azure.storage.blob import BlobServiceClient
            except ImportError as exc:  # pragma: no cover - dependency is in [azure]
                raise StorageError(
                    "Blob storage needs the azure extras; install ccreport[azure]"
                ) from exc
            credential = self._credential or DefaultAzureCredential()
            self._service = BlobServiceClient(self.account_url, credential=credential)
        client = self._service.get_container_client(self.container)
        if not self._ensured:
            try:
                client.create_container()
            except Exception as exc:
                # Already there, or we lack create rights and it was provisioned
                # for us. Either way the next operation reports the real problem.
                logger.debug("container %s not created: %s", self.container, exc)
            self._ensured = True
        return client

    def put(self, path: str, data: bytes, *, content_type: str = "application/octet-stream") -> str:
        from azure.storage.blob import ContentSettings

        _validate(path)
        self._container_client().upload_blob(
            name=path,
            data=data,
            overwrite=True,
            content_settings=ContentSettings(content_type=content_type),
        )
        return path

    def get(self, path: str) -> bytes:
        _validate(path)
        try:
            return self._container_client().download_blob(path).readall()
        except Exception as exc:
            raise StorageError(f"artifact not found: {path}") from exc

    def exists(self, path: str) -> bool:
        _validate(path)
        try:
            return bool(self._container_client().get_blob_client(path).exists())
        except Exception:
            return False

    def delete(self, path: str) -> bool:
        _validate(path)
        try:
            self._container_client().delete_blob(path)
            return True
        except Exception:
            return False

    def delete_prefix(self, prefix: str) -> int:
        _validate(prefix)
        client = self._container_client()
        count = 0
        for blob in client.list_blobs(name_starts_with=prefix.rstrip("/") + "/"):
            client.delete_blob(blob.name)
            count += 1
        return count


def default_local_root(settings: Settings) -> Path:
    if settings.local_artifact_dir:
        return Path(settings.local_artifact_dir).expanduser()
    from .paths import state_dir

    return state_dir() / "artifacts"


def get_artifact_store(settings: Settings | None = None) -> ArtifactStore:
    """Blob when an account URL is configured, a local directory otherwise."""
    settings = settings or get_settings()
    if settings.blob_account_url:
        return BlobArtifactStore(settings.blob_account_url, settings.blob_container)
    return LocalArtifactStore(default_local_root(settings))


__all__ = [
    "ArtifactStore",
    "BlobArtifactStore",
    "LocalArtifactStore",
    "StorageError",
    "artifact_path",
    "get_artifact_store",
    "safe_filename",
]
